(ZENODO BADGE HERE)

# Lagrangian Descriptors: Discovery and Quantification of Phase Space Structure and Transport

**Authors**

Makrina Agaoglou, Broncio Aguilar-Sanjuan, Victor José García Garrido, Francisco González-Montoya, Matthaios Katsanikas, Vladimír Krajňák, Shibabrat Naik, Stephen Wiggins.

Welcome to the GitHub repository! 

## What this book is about?

This book is a collaborative project between researchers in the CHAMPS (Chemistry and Mathematics in Phase Space) research project <https://www.champsproject.com>
Research in CHAMPS is concerned with discovering the geometrical structures in the phase space of dynamical systems that govern the many and varied mechanisms leading to a chemical reaction.  Such dynamical systems are highly nonlinear, often time-dependent (both deterministic and stochastic), and generally high dimensional.  When faced with such a complex dynamical setting, the researcher needs computational techniques for discovering the relevant geometrical structures as well as the theoretical techniques for interpreting the results of computations in the context of specific applications.

## Why did we write this book?

In recent years the method of Lagrangian descriptors has proven a successful computational diagnostic for revealing phase space structure in a wide variety of problems concerned with Lagrangian transport in fluid dynamics and, most recently, to the types of dynamical systems arising in theoretical chemistry that we noted above.

Lagrangian descriptors are a trajectory diagnostic for revealing phase space structures in dynamical systems. The method is very compelling since it is straightforward to implement computationally, the interpretation is evident, and it provides a “high resolution” method for exploring large dimensional phase space with low dimensional slices. In this book, we will illustrate these aspects of Lagrangian descriptors throughout this book.

## Overview

This book is a companion to the previous Jupyter book published by the CHAMPS group <https://www.chemicalreactions.io>. That book was written using the book sprint approach. That was originally the plan for this book, but the coronavirus and the subsequent lockdown intervened, and this project became more of a book marathon. Using our experience from the previous book sprint we tried, as much as possible, to implement the same approach, but through regularly scheduled weekly meetings where assignments were handed out and criticized on a weekly basis.

## Goal and vision

The types of dynamical systems that we consider in this book are Hamiltonian systems, both autonomous (time-independent) and nonautonomous (time-dependent). In Chapters 1 and 2 we describe some of the necessary backgrounds in Hamiltonian systems that are useful for interpreting the output of Lagrangian descriptor calculations for such dynamical systems.  Chapter 3 describes the method of Lagrangian descriptors, both the theoretical settings as well as the history of the method and the current scope of applications. The final part of the book is a collection of Jupyter notebooks that implements the method for a variety of examples.


## Contributing
We view these books as community projects and we invite all those interested to participate in their further development through Github.

Guidelines on how to contribute to this package can be found  [here](https://github.com/champsproject/chem_react_dyn/blob/docs/docs/contributing.md) along with the code of conduct [here](https://github.com/champsproject/chem_react_dyn/blob/docs/docs/CODE_OF_CONDUCT.md) for engaging with the fellow contributors.


## Copyright and License
Copyright 2019

All content is under Creative Commons Attribution [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode.txt) and all the python scripts are under [BSD-3 clause](https://github.com/champsproject/chem_react_dyn/blob/docs/docs/LICENSE).

## References



